export type Project = [number: string, title: string, details: string, period: string];

export const projectsKo: Project[] = [
  ["01", "환자 맞춤형 복부 수술 시뮬레이터", "담낭 절제술용 물리 엔진 및 장기 변형 수학 모델 연구 · 보건복지부 / 한국보건산업진흥원 · 기술자문", "2023.07 – 2023.12"],
  ["02", "전시·컨벤션 통합지원을 위한 실·가상 연동 MICE 플랫폼 개발", "오프라인 전시와 3D 가상전시를 통합하고 AI 방문자 분석·맞춤형 비즈니스 분석을 지원하는 플랫폼 · 한국콘텐츠진흥원 · 공동연구책임자", "2022.04 – 2023.12"],
  ["03", "물리기반 실시간 시뮬레이션 엔진 개발", "XR 환경을 위한 물리기반 실시간 시뮬레이션 엔진 · ㈜휴톰 위탁연구개발", "2021.07 – 2022.12"],
  ["04", "대화형 가상공간 구축을 위한 동적 공간증강현실 도구 개발", "실시간 객체 위치·자세 추정으로 프로젝션 파라미터를 자동 조절하고 변형 객체에도 대응하는 Spatial AR 기술 · 한국연구재단 · 주관연구책임", "2017.06 – 2020.05"],
  ["05", "Adaptive 3D Slicing을 위한 Visual Mesh Saliency Map 생성 라이브러리 성능 최적화", "Visual Mesh Saliency Map 생성 라이브러리 성능 최적화 · ㈜인텔리코리아 · 연구책임", "2016.03 – 2017.02"],
  ["06", "모바일 AR 콘텐츠 빌더 기술 개발", "모바일 증강현실 콘텐츠 저작 기술 개발 · ㈜누리봄 · 연구책임", "2016.01 – 2016.08"],
  ["07", "모바일 디바이스에 적합한 실시간 3D 변형 물체 시뮬레이션 최적화", "모바일 환경을 위한 실시간 3D 변형 물체 시뮬레이션 최적화 · 한국연구재단 기본연구지원사업 · 주관연구책임", "2015.11 – 2017.10"],
  ["08", "3D Slicing 최적화를 위한 Visual Mesh Saliency Map 생성 라이브러리 구현", "Visual Mesh Saliency Map 생성 라이브러리 구현 · 용역과제책임", "2015.03 – 2016.02"],
  ["09", "모바일 AR 교육 콘텐츠 프로토타입 설계 및 구현", "모바일 AR 교육 콘텐츠 프로토타입 설계 및 구현 · KGIT X-Program · 과제책임교수", "2013.03 – 2014.12"],
  ["10", "가상객체의 인터랙티브 움직임 표현을 위한 실시간 물리기반 모델링", "실시간 물리기반 가상객체 인터랙션 모델링 · KGIT X-Program · 과제책임교수", "2014.09 – 2014.12"],
  ["11", "HMD 기반 몰입형 가상현실 시스템에서의 영상 왜곡 보정 알고리즘 설계", "HMD 기반 몰입형 VR 영상 왜곡 보정 알고리즘 · KGIT X-Program · 과제책임교수", "2014.09 – 2014.12"],
  ["12", "멀티터치 스크린 기반의 인터랙티브 콘텐츠 설계 및 구현", "멀티터치 스크린 기반 인터랙티브 콘텐츠 설계 및 구현 · KGIT X-Program · 과제책임교수", "2014.03 – 2014.08"],
  ["13", "무안경방식의 모바일 입체 콘텐츠 뷰어의 설계 및 구현", "무안경 방식 모바일 입체 콘텐츠 뷰어 설계 및 구현 · KGIT X-Program · 과제책임교수", "2013.09 – 2014.08"],
  ["14", "Advanced Active Auto Tracking 기술 개발", "Advanced Active Auto Tracking 기술 개발 · ㈜제론헬스케어 위탁과제 · 위탁과제책임자", "2012.10 – 2013.09"],
  ["15", "Active Auto Tracking 기술 개발", "Active Auto Tracking 기술 개발 · ㈜제론헬스케어 위탁과제 · 위탁과제책임자", "2011.10 – 2012.09"],
  ["16", "스포츠방송용 Active Stromotion System 개발", "스포츠방송용 Active Stromotion System 개발 · 구매조건부 신제품개발사업 · 위탁과제책임자", "2010.09 – 2011.08"],
  ["17", "Interactive Media Art를 위한 Mobile AR 기술 개발", "인터랙티브 미디어아트를 위한 Mobile AR 기술 개발 · 인천국제디지털아트페스티벌 위탁연구과제 · 위탁과제책임자", "2010.05 – 2010.09"],
  ["18", "지능형 출입 감시를 위한 이동 객체 특성 분석 기술 개발", "지능형 출입 감시를 위한 이동 객체 특성 분석 · 지식경제부 / 21세기 프론티어 유비쿼터스컴퓨팅 및 네트워크 사업 · 위탁과제책임자", "2010.03 – 2010.12"],
  ["19", "단일 카메라 기반 다중 사용자 제스처 인터랙션 기술 개발", "단일 카메라 기반 다중 사용자 제스처 인터랙션 기술 · 학술진흥재단 / 과학재단 지원사업 · 과제책임자", "2009.05 – 2010.04"],
  ["20", "CCTV 카메라 영상 지능화 검색 기술 개발", "CCTV 카메라 영상 지능화 검색 기술 · 지식경제부 / 21세기 프론티어 유비쿼터스컴퓨팅 및 네트워크 사업 · 위탁과제책임자", "2009.01 – 2009.12"],
  ["21", "IPTV를 위한 3D Editor 개발", "IPTV용 3D Editor 개발 · 호서대학교 벤처연구사업 · 공동연구원", "2008.08 – 2010.07"],
  ["22", "다중 카메라에서의 동일인 식별을 위한 의상 특성 분석", "다중 카메라 동일인 식별을 위한 의상 특성 분석 · 지식경제부 / 21세기 프론티어 유비쿼터스컴퓨팅 및 네트워크 사업 · 공동과제책임자", "2008.01 – 2008.12"],
  ["23", "스마트 감시 시스템을 위한 관심 행위 인지 기술", "스마트 감시 시스템을 위한 관심 행위 인지 기술 · 정보통신부 / 21세기 프론티어 유비쿼터스컴퓨팅 및 네트워크 사업 · 위탁과제책임자", "2007.04 – 2007.12"],
  ["24", "3D Vision 기반 Hair Simulation 기술 개발", "3D Vision 기반 Hair Simulation 기술 · 중소기업청 중소기업기술혁신개발사업 · 위탁과제책임자", "2006.08 – 2007.07"],
  ["25", "비전기반 3차원 인터랙션 도구 및 변형 모델의 입체조작 기술 개발", "비전기반 3차원 인터랙션 및 변형 모델 입체조작 기술 · 한국학술진흥재단 신진교수지원사업 · 과제책임자", "2006.07 – 2008.06"],
  ["26", "스마트 스페이스를 위한 제스처 인터랙션 기술 개발", "스마트 스페이스를 위한 제스처 인터랙션 기술 · 정보통신부 / 21세기 프론티어 유비쿼터스컴퓨팅 및 네트워크 사업 · 위탁과제책임자", "2006.04 – 2007.03"],
  ["27", "사용자 적응형 인터랙티브 유비쿼터스 인터페이스 및 마이그레이션 기술 개발", "사용자 적응형 인터랙티브 유비쿼터스 인터페이스 및 마이그레이션 기술 · 정보통신부 / 21세기 프론티어 사업 · 위탁과제책임자", "2005.04 – 2006.03"],
  ["28", "디스플레이 및 이동 통신 산업의 최근 동향과 관련 핵심 부품 산업의 동향 분석", "디스플레이·이동통신 산업 및 핵심 부품 산업 동향 분석 · 신흥하이텍 지원과제 · 과제책임자", "2006.02 – 2006.05"],
  ["29", "의료영상정보의 복합적 비주얼 컴퓨팅 기술개발", "의료영상정보의 복합적 비주얼 컴퓨팅 기술개발 · 과학기술부 지원과제 · 참여연구원", "2000.06 – 2005.03"],
];

export const projectsEn: Project[] = [
  ["01", "Patient-specific abdominal surgery simulator", "Physics engine for cholecystectomy and mathematical models of organ deformation · Ministry of Health and Welfare / KHIDI · Technical advisor", "2023.07 – 2023.12"],
  ["02", "Hybrid MICE platform for integrated exhibition and convention support", "A platform integrating physical and 3D virtual exhibitions with AI-based visitor and business-opportunity analysis · KOCCA · Co-principal investigator", "2022.04 – 2023.12"],
  ["03", "Physics-based real-time simulation engine", "Physics-based real-time simulation engine for XR environments · Hutom commissioned R&D", "2021.07 – 2022.12"],
  ["04", "Dynamic spatial augmented reality tools for interactive virtual environments", "Spatial AR that automatically adjusts projection parameters through real-time object pose estimation, including deformable objects · National Research Foundation of Korea · Principal investigator", "2017.06 – 2020.05"],
  ["05", "Performance optimization of a Visual Mesh Saliency Map library for adaptive 3D slicing", "Performance optimization of a Visual Mesh Saliency Map generation library · Intelli Korea · Principal investigator", "2016.03 – 2017.02"],
  ["06", "Mobile AR content builder technology", "Mobile augmented-reality content authoring technology · Nuribom · Principal investigator", "2016.01 – 2016.08"],
  ["07", "Optimization of real-time 3D deformable-object simulation for mobile devices", "Optimization for mobile real-time 3D deformable-object simulation · National Research Foundation of Korea · Principal investigator", "2015.11 – 2017.10"],
  ["08", "Visual Mesh Saliency Map library for 3D slicing optimization", "Implementation of a Visual Mesh Saliency Map generation library · Service project lead", "2015.03 – 2016.02"],
  ["09", "Mobile AR educational-content prototype", "Design and implementation of a mobile AR educational-content prototype · KGIT X-Program · Project professor", "2013.03 – 2014.12"],
  ["10", "Real-time physics-based modeling for interactive virtual-object motion", "Real-time physics-based modeling for virtual-object interaction · KGIT X-Program · Project professor", "2014.09 – 2014.12"],
  ["11", "Image-distortion correction for HMD-based immersive VR", "Design of image-distortion correction algorithms for HMD-based immersive VR · KGIT X-Program · Project professor", "2014.09 – 2014.12"],
  ["12", "Interactive content using multi-touch screens", "Design and implementation of multi-touch-screen-based interactive content · KGIT X-Program · Project professor", "2014.03 – 2014.08"],
  ["13", "Glasses-free mobile stereoscopic-content viewer", "Design and implementation of a glasses-free mobile stereoscopic-content viewer · KGIT X-Program · Project professor", "2013.09 – 2014.08"],
  ["14", "Advanced Active Auto Tracking", "Advanced Active Auto Tracking technology · Xerion Healthcare commissioned project · Project lead", "2012.10 – 2013.09"],
  ["15", "Active Auto Tracking", "Active Auto Tracking technology · Xerion Healthcare commissioned project · Project lead", "2011.10 – 2012.09"],
  ["16", "Active Stromotion System for sports broadcasting", "Active Stromotion System for sports broadcasting · Conditional new-product development program · Project lead", "2010.09 – 2011.08"],
  ["17", "Mobile AR for interactive media art", "Mobile AR technology for interactive media art · Incheon International Digital Art Festival commissioned research · Project lead", "2010.05 – 2010.09"],
  ["18", "Moving-object feature analysis for intelligent entrance surveillance", "Moving-object feature analysis for intelligent entrance surveillance · Ministry of Knowledge Economy / 21st Century Frontier Program · Project lead", "2010.03 – 2010.12"],
  ["19", "Multi-user gesture interaction with a single camera", "Single-camera multi-user gesture interaction · Korea Research Foundation / Science Foundation support · Project lead", "2009.05 – 2010.04"],
  ["20", "Intelligent CCTV video search", "Intelligent CCTV video-search technology · Ministry of Knowledge Economy / 21st Century Frontier Program · Project lead", "2009.01 – 2009.12"],
  ["21", "3D editor for IPTV", "3D editor development for IPTV · Hoseo University venture research project · Co-researcher", "2008.08 – 2010.07"],
  ["22", "Clothing-feature analysis for person identification across multiple cameras", "Clothing-feature analysis for multi-camera person identification · Ministry of Knowledge Economy / 21st Century Frontier Program · Co-project lead", "2008.01 – 2008.12"],
  ["23", "Behavior recognition for smart-surveillance systems", "Recognition of events of interest for smart surveillance · Ministry of Information and Communication / 21st Century Frontier Program · Project lead", "2007.04 – 2007.12"],
  ["24", "3D Vision-based hair simulation", "3D Vision-based hair-simulation technology · Small and Medium Business Administration technology-innovation program · Project lead", "2006.08 – 2007.07"],
  ["25", "Vision-based 3D interaction tools and stereoscopic manipulation of deformable models", "Vision-based 3D interaction and deformable-model manipulation · Korea Research Foundation young-professor program · Project lead", "2006.07 – 2008.06"],
  ["26", "Gesture interaction for smart spaces", "Gesture-interaction technology for smart spaces · Ministry of Information and Communication / 21st Century Frontier Program · Project lead", "2006.04 – 2007.03"],
  ["27", "User-adaptive interactive ubiquitous interfaces and migration", "User-adaptive interactive ubiquitous-interface and migration technology · Ministry of Information and Communication / 21st Century Frontier Program · Project lead", "2005.04 – 2006.03"],
  ["28", "Trend analysis for display, mobile communications, and core-component industries", "Trend analysis of display and mobile-communications industries and related core components · Shinheung Hi-Tech support project · Project lead", "2006.02 – 2006.05"],
  ["29", "Integrated visual-computing technology for medical-image information", "Integrated visual-computing technology for medical-image information · Ministry of Science and Technology support project · Participating researcher", "2000.06 – 2005.03"],
];
